default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode 
  timeout: 5000 
  username: postgres
  password: mysecretpassword
  host: postgres
  port: 5432
  
development:
  adapter: postgresql
  pool: 5
  encoding: unicode 
  timeout: 5000 
  username: postgres
  password: mysecretpassword
  host: postgres
  port: 5432

test:
  pool: 5
  timeout: 5000
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: 'dictionary'